name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: [ubuntu-latest]
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_FILE: docker-compose.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: make build
      - name: Full check
        run: make full-check
